version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  microservico_cadastro:
    build:
      context: ./cadastro
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
  
  microservico_notificacao:
    build:
      context: ./notificacao
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
