services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  microservico_pagar:
    build:
      context: ./pagar/pagar
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
  
  microservico_notificacao:
    build:
      context: ./notificar/notificar
    ports:
      - "8082:8083"
    depends_on:
      - rabbitmq
